//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeConhecimento
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspectosPorProjeto
    {
        public int idProjeto { get; set; }
        public int idAspecto { get; set; }
        public Nullable<int> prioridade { get; set; }
        public decimal pesoAtribuido { get; set; }
    
        public virtual Aspectos Aspectos { get; set; }
        public virtual Projeto Projeto { get; set; }
    }
}
