//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeConhecimento
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicoesAprendidas
    {
        public int idLicaoAprendida { get; set; }
        public Nullable<int> avaliacao { get; set; }
        public string descricao { get; set; }
        public string acao { get; set; }
        public Nullable<int> responsavel { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
        public Nullable<int> idProjeto { get; set; }
    
        public virtual Projeto Projeto { get; set; }
    }
}
