//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeConhecimento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas
    {
        public int idNota { get; set; }
        public string nota { get; set; }
        public Nullable<System.DateTime> dataCriacao { get; set; }
        public Nullable<int> idAtividade { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual Atividades Atividades { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
