//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeConhecimento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto
    {
        public Projeto()
        {
            this.AspectosPorProjeto = new HashSet<AspectosPorProjeto>();
            this.TecnologiaPorUsuario = new HashSet<TecnologiaPorUsuario>();
            this.Tags = new HashSet<Tags>();
            this.LicoesAprendidas = new HashSet<LicoesAprendidas>();
            this.Requisito = new HashSet<Requisito>();
        }
    
        public int idProjeto { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> dataPrevistaInicio { get; set; }
        public Nullable<System.DateTime> dataPrevistaTermino { get; set; }
        public Nullable<decimal> custoPrevisto { get; set; }
        public Nullable<decimal> custoReal { get; set; }
        public Nullable<System.DateTime> dataInicio { get; set; }
        public Nullable<System.DateTime> dataFim { get; set; }
    
        public virtual ICollection<AspectosPorProjeto> AspectosPorProjeto { get; set; }
        public virtual ICollection<TecnologiaPorUsuario> TecnologiaPorUsuario { get; set; }
        public virtual ICollection<Tags> Tags { get; set; }
        public virtual ICollection<LicoesAprendidas> LicoesAprendidas { get; set; }
        public virtual ICollection<Requisito> Requisito { get; set; }
    }
}
