//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeConhecimento
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.EnterpriseServices;

    public partial class Projeto
    {
        public Projeto()
        {
            this.AspectosPorProjeto = new HashSet<AspectosPorProjeto>();
            this.TecnologiaPorUsuario = new HashSet<TecnologiaPorUsuario>();
            this.Tags = new HashSet<Tags>();
            this.LicoesAprendidas = new HashSet<LicoesAprendidas>();
            this.Requisito = new HashSet<Requisito>();
        }

        public int idProjeto { get; set; }
        [Required(ErrorMessage="Informe o título do projeto")]
        [Display(Name = "Título")]
        public string titulo { get; set; }
        [Required(ErrorMessage="Informe a descrição do projeto")]
        [Display(Name = "Descrição")]
        public string descricao { get; set; }

        [Display(Name = "Data de previsão início")]
        public Nullable<System.DateTime> dataPrevistaInicio { get; set; }

        [Display(Name = "Data de previsão término")]
        public Nullable<System.DateTime> dataPrevistaTermino { get; set; }

        [Display(Name = "Custo previsto")]
        public Nullable<decimal> custoPrevisto { get; set; }

        [Display(Name = "Custo real")]
        public Nullable<decimal> custoReal { get; set; }

        [Display(Name = "Data início")]
        public Nullable<System.DateTime> dataInicio { get; set; }

        [Display(Name = "Data fim")]
        public Nullable<System.DateTime> dataFim { get; set; }

        public virtual ICollection<AspectosPorProjeto> AspectosPorProjeto { get; set; }
        public virtual ICollection<TecnologiaPorUsuario> TecnologiaPorUsuario { get; set; }
        public virtual ICollection<Tags> Tags { get; set; }
        public virtual ICollection<LicoesAprendidas> LicoesAprendidas { get; set; }
        public virtual ICollection<Requisito> Requisito { get; set; }
    }
}
