//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeConhecimento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisito
    {
        public int idRequisito { get; set; }
        public Nullable<int> idProjeto { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string criterioAceitacao { get; set; }
        public Nullable<int> bugs { get; set; }
        public Nullable<int> qtdComunicacaoExterna { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
    
        public virtual Projeto Projeto { get; set; }
    }
}
