//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeConhecimento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags
    {
        public Tags()
        {
            this.Atividades = new HashSet<Atividades>();
            this.Projeto = new HashSet<Projeto>();
        }
    
        public int idTag { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<Atividades> Atividades { get; set; }
        public virtual ICollection<Projeto> Projeto { get; set; }
    }
}
