//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeConhecimento
{
    using System;
    using System.Collections.Generic;
    
    public partial class TecnologiaPorUsuario
    {
        public int idTecnologiaPorUsuario { get; set; }
        public Nullable<int> idTecnologia { get; set; }
        public Nullable<int> idProjeto { get; set; }
        public Nullable<int> nivelDeConhecimento { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual Projeto Projeto { get; set; }
        public virtual Tecnologia Tecnologia { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
