//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeConhecimento
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Notas = new HashSet<Notas>();
            this.TecnologiaPorUsuario = new HashSet<TecnologiaPorUsuario>();
        }
    
        public int idUsuario { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<Notas> Notas { get; set; }
        public virtual ICollection<TecnologiaPorUsuario> TecnologiaPorUsuario { get; set; }
    }
}
